### PR TITLE
add BLST_PORTABLE to CGO_CFLAGS to fix SIGILL issue with blst

### PR DESCRIPTION
**Pull request by roberto-bayardo**
Fixes issue seen in https://github.com/Inphi/eip4844-interop/pull/48

### CODE REVIEW

**Review by Inphi — APPROVED** [review]
thanks

**Comment by Inphi** [comment]
one qq; is docker meant to directly consume the .env fille? I couldn't find any documentation on how workflows use it

**Comment by roberto-bayardo** [comment]
https://docs.docker.com/compose/environment-variables/ 

This is where I saw it mentioned.

**Comment by Inphi** [comment]
i could be wrong, but i think the working directory of ci/docker is at the project root. The .env won't be picked up unless you move it to the root.

**Comment by roberto-bayardo** [comment]
Ok let me see if the test will fail if I comment it out.

**Comment by roberto-bayardo** [comment]
Yeah test is passing regardless, I guess we're back on a more modern CPU for our builds!  I moved it into the ci.yml file via an "env:" section which I suppose is better anyway (more explicit).

**Comment by Inphi** [comment]
I dont think this will work either because docker doesnt use the env of the caller/parent process for runs.

I'd update the go docker script to provide the env file.

**Comment by roberto-bayardo** [comment]
Ugg good point. I didn't want to put it in the dockerfile since I was hoping to scope it only to the CI, but perhaps that's the simplest solution.  In fact it's already in the dockerfile only commented out!

**Comment by Inphi** [comment]
yeah updating the Dockerfile sounds fine by me.

**Comment by roberto-bayardo** [comment]
@Inphi ptal I believe this should work while isolating it to the CI

**Review by Inphi — APPROVED** [review]
LGTM

**Pull request merged**
