### PR TITLE
Add Lodestar

### PR DESCRIPTION
**Pull request by dgcoffman**
1. Integrates Lodestar from https://github.com/dgcoffman/lodestar/pull/1
2. Modifies the existing tests to pass against Prysm without using its proprietary gRPC API, so the same tests can be run against Lodestar.

TODO
 - [x] Add Lodestar directory, git submodule, chain config, Docker setup
 - [x] Existing `go run ./tests/...` tests all pass 
 - [x] `go run ./tests/pre-4844 lodestar` passes

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
I know this is still a WIP but you might submit this PR against the recently-created devnet-v3 branch instead of master?

**Comment by Inphi** [comment]
Seconded @roberto-bayardo . Let's have this target the devnet-v3 branch.

**Comment by roberto-bayardo** [comment]
keep in mind that we haven't updated prysm/geth for the latest (3038) protocol changes so it might not play nice just yet with the other clients.  I'll get that done soon though.

**Comment by dgcoffman** [comment]
https://github.com/Inphi/eip4844-interop/pull/52

**Pull request closed without merging**
