### PR TITLE
Set SLOTS_PER_EPOCH to minimal value

### PR DESCRIPTION
**Pull request by dapplion**
un-curse interop

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
didn't we want to change this to the mainnet value (32)?

**Comment by roberto-bayardo** [comment]
cc: @Inphi

**Comment by Inphi** [comment]
> didn't we want to change this to the mainnet value (32)?

yeah I thought we agreed to set SLOTS_PER_EPOCH to mainnet's. There are clients rely on hardcoded presets. We don't wanna use the minimal preset because that means their `FIELD_ELEMENTS_PER_BLOB` config is no longer 4096.

**Comment by Inphi** [comment]
We've changed the preset to use mainnet via https://github.com/Inphi/eip4844-interop/pull/71. Closing.

**Pull request closed without merging**
