### PR TITLE
Make all beacon chain config values explicit and move to common directory

### PR DESCRIPTION
**Pull request by jimmygchen**
Prysm populate mainnet config values by default if any value is not supplied. 

This behaviour does not exist on other clients (Teku, Lighthouse afaik). Making these explicit in the common beacon config will allow all other clients to easily reuse them.

### CODE REVIEW

**Review by roberto-bayardo — APPROVED** [review]
this is great thank you.

**Comment by roberto-bayardo** [comment]
Oh hm this is breaking the continuous build tests; looks like the prysm beacon nodes might not be coming up? Does the failing test (go run ./tests/pre-4844) pass for you locally?

**Comment by jimmygchen** [comment]
> Oh hm this is breaking the continuous build tests; looks like the prysm beacon nodes might not be coming up? Does the failing test (go run ./tests/pre-4844) pass for you locally?

Hi @roberto-bayardo thanks for the looking into this! I'll try running the tests locally. Not sure if `PRESET_BASE` config location in the file matters, but I should probably go with the convention and move it to the top of file

**Comment by jimmygchen** [comment]
@roberto-bayardo 

~~after moving `PRESET_BASE` to the top, the test runs locally now without any error.. so it seems like the order matters~~

**EDIT:** I just reverted the change and the test still passes 😅 let me take a look again on the CI logs..

```
2022/11/05 23:47:50 waiting for geth
2022/11/05 23:47:57 waiting for prysm beacon node
2022/11/05 23:48:00 waiting for prysm beacon node follower
2022/11/05 23:48:06 waiting for validator
2022/11/05 23:48:06 Nonce: 0
2022/11/05 23:48:06 Waiting for transaction (0xf6e4d98e2d071638d7c9d15a1ab7a70f03536d4ce39d1b8137b7e6123fda89cb) to be included...
```

**Comment by roberto-bayardo** [comment]
@jimmygchen make sure you run "make devnet-clean" or similar to force a rebuild between changes!  I have made that mistake many a time....  the current scripts aren't smart enough to rebuild what's needed when you make changes to the subrepos.

**Comment by roberto-bayardo** [comment]
Hmm tests are working for me locally when I include your PR.  Wonder if the CI config needs to be updated somehow.

**Comment by roberto-bayardo** [comment]
I think our timeout is just too short... maybe they started running the CIs on slower machines! I will try doubling it.

**Comment by roberto-bayardo** [comment]
Ahah, they seem to be running the CI on older processors without the instructions expected

+ beacon-node --accept-terms-of-use --verbosity=debug --datadir /chaindata --force-clear-db --interop-eth1data-votes --http-web3provider=http://execution-node:8545 --deposit-contract 0x8A04d14125D0FDCDc742F4A05C051De07232EDa4 --chain-config-file=/config/chain-config.yml --contract-deployment-block 0 --interop-num-validators 4 --rpc-host 0.0.0.0 --rpc-port 4000 --grpc-gateway-host 0.0.0.0 --grpc-gateway-port 3500 --enable-debug-rpc-endpoints --p2p-local-ip 0.0.0.0 --p2p-host-ip 172.18.0.5 --p2p-priv-key=/etc/prysm-priv-key --subscribe-all-subnets --enable-tracing --tracing-endpoint http://jaeger-tracing:14268/api/traces --tracing-process-name beacon-node --min-sync-peers=0 --bootstrap-node=
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.

@jimmygchen I will fix this later.. feel free to merge (you can back out my timeout update & the PRESET_BASE change if you liike)

**Comment by jimmygchen** [comment]
ahh nice catch. Thanks for looking into this! I'll revert the timeout changes and keep the `PRESET_BASE` as it is since most config files have them on the top anyways.

**Pull request merged**
